mkdir -p geometry/common geometry/scene_graph meshcat perception/common
git mv geometry/proximity/sorted_triplet.cc common/sorted_triplet.cc
git mv geometry/proximity/sorted_triplet.h common/sorted_triplet.h
git mv geometry/collision_filter_declaration.cc geometry/common/collision_filter_declaration.cc
git mv geometry/collision_filter_declaration.h geometry/common/collision_filter_declaration.h
git mv geometry/deformable_mesh.cc geometry/common/deformable_mesh.cc
git mv geometry/deformable_mesh.h geometry/common/deformable_mesh.h
git mv geometry/geometry_frame.cc geometry/common/geometry_frame.cc
git mv geometry/geometry_frame.h geometry/common/geometry_frame.h
git mv geometry/geometry_ids.h geometry/common/geometry_ids.h
git mv geometry/geometry_instance.cc geometry/common/geometry_instance.cc
git mv geometry/geometry_instance.h geometry/common/geometry_instance.h
git mv geometry/geometry_properties.cc geometry/common/geometry_properties.cc
git mv geometry/geometry_properties.h geometry/common/geometry_properties.h
git mv geometry/geometry_roles.cc geometry/common/geometry_roles.cc
git mv geometry/geometry_roles.h geometry/common/geometry_roles.h
git mv geometry/geometry_set.h geometry/common/geometry_set.h
git mv geometry/geometry_version.cc geometry/common/geometry_version.cc
git mv geometry/geometry_version.h geometry/common/geometry_version.h
git mv geometry/internal_frame.h geometry/common/internal_frame.h
git mv geometry/kinematics_vector.cc geometry/common/kinematics_vector.cc
git mv geometry/kinematics_vector.h geometry/common/kinematics_vector.h
git mv geometry/proximity/mesh_deformer.cc geometry/common/mesh_deformer.cc
git mv geometry/proximity/mesh_deformer.h geometry/common/mesh_deformer.h
git mv geometry/proximity/mesh_field_linear.h geometry/common/mesh_field_linear.h
git mv geometry/proximity/mesh_traits.h geometry/common/mesh_traits.h
git mv geometry/proximity/obj_to_surface_mesh.cc geometry/common/obj_to_surface_mesh.cc
git mv geometry/proximity/obj_to_surface_mesh.h geometry/common/obj_to_surface_mesh.h
git mv geometry/proximity/polygon_surface_mesh.cc geometry/common/polygon_surface_mesh.cc
git mv geometry/proximity/polygon_surface_mesh.h geometry/common/polygon_surface_mesh.h
git mv geometry/proximity/polygon_surface_mesh_field.cc geometry/common/polygon_surface_mesh_field.cc
git mv geometry/proximity/polygon_surface_mesh_field.h geometry/common/polygon_surface_mesh_field.h
git mv geometry/proximity_properties.cc geometry/common/proximity_properties.cc
git mv geometry/proximity_properties.h geometry/common/proximity_properties.h
git mv geometry/read_obj.cc geometry/common/read_obj.cc
git mv geometry/read_obj.h geometry/common/read_obj.h
git mv geometry/rgba.cc geometry/common/rgba.cc
git mv geometry/rgba.h geometry/common/rgba.h
git mv geometry/shape_specification.cc geometry/common/shape_specification.cc
git mv geometry/shape_specification.h geometry/common/shape_specification.h
git mv geometry/shape_to_string.cc geometry/common/shape_to_string.cc
git mv geometry/shape_to_string.h geometry/common/shape_to_string.h
git mv geometry/proximity/triangle_surface_mesh.cc geometry/common/triangle_surface_mesh.cc
git mv geometry/proximity/triangle_surface_mesh.h geometry/common/triangle_surface_mesh.h
git mv geometry/proximity/triangle_surface_mesh_field.cc geometry/common/triangle_surface_mesh_field.cc
git mv geometry/proximity/triangle_surface_mesh_field.h geometry/common/triangle_surface_mesh_field.h
git mv geometry/utilities.cc geometry/common/utilities.cc
git mv geometry/utilities.h geometry/common/utilities.h
git mv geometry/proximity/volume_mesh.cc geometry/common/volume_mesh.cc
git mv geometry/proximity/volume_mesh.h geometry/common/volume_mesh.h
git mv geometry/proximity/volume_mesh_field.cc geometry/common/volume_mesh_field.cc
git mv geometry/proximity/volume_mesh_field.h geometry/common/volume_mesh_field.h
git mv geometry/proximity/volume_to_surface_mesh.cc geometry/common/volume_to_surface_mesh.cc
git mv geometry/proximity/volume_to_surface_mesh.h geometry/common/volume_to_surface_mesh.h
git mv geometry/deformable_mesh_with_bvh.cc geometry/proximity/deformable_mesh_with_bvh.cc
git mv geometry/deformable_mesh_with_bvh.h geometry/proximity/deformable_mesh_with_bvh.h
git mv geometry/render/shaders/depth_shaders.h geometry/render_vtk/internal_depth_shaders.h
git mv geometry/collision_filter_manager.cc geometry/scene_graph/collision_filter_manager.cc
git mv geometry/collision_filter_manager.h geometry/scene_graph/collision_filter_manager.h
git mv geometry/geometry_state.cc geometry/scene_graph/geometry_state.cc
git mv geometry/geometry_state.h geometry/scene_graph/geometry_state.h
git mv geometry/internal_frame.cc geometry/scene_graph/internal_frame.cc
git mv geometry/internal_geometry.cc geometry/scene_graph/internal_geometry.cc
git mv geometry/internal_geometry.h geometry/scene_graph/internal_geometry.h
git mv geometry/make_mesh_for_deformable.cc geometry/scene_graph/make_mesh_for_deformable.cc
git mv geometry/make_mesh_for_deformable.h geometry/scene_graph/make_mesh_for_deformable.h
git mv geometry/proximity_engine.cc geometry/scene_graph/proximity_engine.cc
git mv geometry/proximity_engine.h geometry/scene_graph/proximity_engine.h
git mv geometry/query_object.cc geometry/scene_graph/query_object.cc
git mv geometry/query_object.h geometry/scene_graph/query_object.h
git mv geometry/scene_graph.cc geometry/scene_graph/scene_graph.cc
git mv geometry/scene_graph.h geometry/scene_graph/scene_graph.h
git mv geometry/scene_graph_inspector.cc geometry/scene_graph/scene_graph_inspector.cc
git mv geometry/scene_graph_inspector.h geometry/scene_graph/scene_graph_inspector.h
git mv systems/primitives/linear_system_internal.cc math/linear_system_internal.cc
git mv systems/primitives/linear_system_internal.h math/linear_system_internal.h
git mv geometry/meshcat.cc meshcat/meshcat.cc
git mv geometry/meshcat.h meshcat/meshcat.h
git mv geometry/meshcat.html meshcat/meshcat.html
git mv geometry/meshcat_animation.cc meshcat/meshcat_animation.cc
git mv geometry/meshcat_animation.h meshcat/meshcat_animation.h
git mv geometry/meshcat_file_storage_internal.cc meshcat/meshcat_file_storage_internal.cc
git mv geometry/meshcat_file_storage_internal.h meshcat/meshcat_file_storage_internal.h
git mv geometry/meshcat_graphviz.cc meshcat/meshcat_graphviz.cc
git mv geometry/meshcat_graphviz.h meshcat/meshcat_graphviz.h
git mv geometry/meshcat_internal.cc meshcat/meshcat_internal.cc
git mv geometry/meshcat_internal.h meshcat/meshcat_internal.h
git mv geometry/meshcat_types_internal.h meshcat/meshcat_types_internal.h
git mv systems/sensors/camera_info.cc perception/common/camera_info.cc
git mv systems/sensors/camera_info.h perception/common/camera_info.h
git mv systems/sensors/image.cc perception/common/image.cc
git mv systems/sensors/image.h perception/common/image.h
git mv systems/sensors/image_file_format.cc perception/common/image_file_format.cc
git mv systems/sensors/image_file_format.h perception/common/image_file_format.h
git mv systems/sensors/image_io.h perception/common/image_io.h
git mv systems/sensors/image_io_internal.cc perception/common/image_io_internal.cc
git mv systems/sensors/image_io_internal.h perception/common/image_io_internal.h
git mv systems/sensors/image_io_load.cc perception/common/image_io_load.cc
git mv systems/sensors/image_io_save.cc perception/common/image_io_save.cc
git mv systems/sensors/pixel_types.cc perception/common/pixel_types.cc
git mv systems/sensors/pixel_types.h perception/common/pixel_types.h
git mv systems/sensors/vtk_diagnostic_event_observer.cc perception/common/vtk_diagnostic_event_observer.cc
git mv systems/sensors/vtk_diagnostic_event_observer.h perception/common/vtk_diagnostic_event_observer.h
git mv systems/sensors/vtk_image_reader_writer.cc perception/common/vtk_image_reader_writer.cc
git mv systems/sensors/vtk_image_reader_writer.h perception/common/vtk_image_reader_writer.h
git mv multibody/meshcat/contact_visualizer.cc visualization/contact_visualizer.cc
git mv multibody/meshcat/contact_visualizer.h visualization/contact_visualizer.h
git mv multibody/meshcat/contact_visualizer_params.h visualization/contact_visualizer_params.h
git mv geometry/drake_visualizer.cc visualization/drake_visualizer.cc
git mv geometry/drake_visualizer.h visualization/drake_visualizer.h
git mv geometry/drake_visualizer_params.h visualization/drake_visualizer_params.h
git mv multibody/meshcat/hydroelastic_contact_visualizer.cc visualization/hydroelastic_contact_visualizer.cc
git mv multibody/meshcat/hydroelastic_contact_visualizer.h visualization/hydroelastic_contact_visualizer.h
git mv multibody/meshcat/joint_sliders.cc visualization/joint_sliders.cc
git mv multibody/meshcat/joint_sliders.h visualization/joint_sliders.h
git mv geometry/meshcat_point_cloud_visualizer.cc visualization/meshcat_point_cloud_visualizer.cc
git mv geometry/meshcat_point_cloud_visualizer.h visualization/meshcat_point_cloud_visualizer.h
git mv geometry/meshcat_visualizer.cc visualization/meshcat_visualizer.cc
git mv geometry/meshcat_visualizer.h visualization/meshcat_visualizer.h
git mv geometry/meshcat_visualizer_params.h visualization/meshcat_visualizer_params.h
git mv multibody/meshcat/point_contact_visualizer.cc visualization/point_contact_visualizer.cc
git mv multibody/meshcat/point_contact_visualizer.h visualization/point_contact_visualizer.h
